### ISSUE TITLE
Allow percentages in the geometry

### ISSUE THREAD

**Issue by omixann** [phillbush/xprompt#1]
This would allow resolution-independent sizing and positioning. For example, `-g 20%x32` would make a bar 32 pixels high and 20% of the horizontal resolution wide.

**Comment by phillbush** [comment]
That's a great idea, I'm gonna implement it in the next release.

**Comment by phillbush** [comment]
I would have to implement a parsing routine to parse the new geometry specification (for now, xprompt uses `XParseGeometry(3)` to parse it). But it would be easy to do. I'm gonna implement it in the next release.

**Comment by phillbush** [comment]
I've just added support for geometry relative to the monitor size with percentages.

**Comment by Veraellyunjie** [comment]
> sizing **and positioning**

`-g 20%x32-20-0` - this works
`-g 20%x32-20%-0` - `xprompt: improper geometry specification 20%x32-20%-0`
