### ISSUE TITLE
Visual corruption when no prompt is specified

### ISSUE THREAD

**Issue by omixann** [phillbush/xprompt#2]
I've noticed that if you don't specify a prompt, there are visual glitches on the left side of the bar. The content is different between runs.

**Comment by phillbush** [comment]
That's strange, I have not seen any of those glitches in my machine.  
What arguments did you passed to xprompt?  
Can you share a screenshot of how it looks? (xprompt grabs the keyboard, so for taking a screenshot you should delay the screenshot for some seconds, say 5 sec, such as `scrot -d 5 screenshot.png`).
Also, show your font configuration (the left padding of xprompt depends on the height of the first font).

**Comment by omixann** [comment]
Ok, I've had some problems reproducing it after restarting my X session, but I've managed to get it again.

- Command: `./xprompt -G C -g 800x32` (I got it to glitch after changing the geometry around a few times though)
- Font: `DejaVu Sans:size=11`

Here you have a picture, but it doesn't always look the same. This one look almost intended, the previous one was like random noise
![2020-08-06-184712_1920x1080_scrot](https://user-images.githubusercontent.com/17623703/89570314-54209600-d826-11ea-806c-3677423e7a80.png)

**Comment by phillbush** [comment]
I did some changes in how the background of the prompt string is drawn, hopefully this will fix this problem. Can you test if it now runs right?

**Comment by omixann** [comment]
It seems to be working! I've juggled the coordinates around and it doesn't glitch. I'll close the issue, if I see it glitches again I'll just reopen it.

**Comment by phillbush** [comment]
Ok.
I accidentally closed that issue earlier. My fault.
The problem was that xprompt wasn't drawing the background of the prompt string, so it grabbed garbage on the display to be its background.
